{"version":3,"file":"catchAsyncError.js","sourceRoot":"/","sources":["src/shared/catchAsyncError.ts"],"names":[],"mappings":";;AAEA,MAAM,UAAU,GACd,CAAC,EAAkB,EAAE,EAAE,CACvB,KAAK,EAAE,GAAY,EAAE,GAAa,EAAE,IAAkB,EAAiB,EAAE;IACvE,IAAI,CAAC;QACH,MAAM,EAAE,CAAC,GAAG,EAAE,GAAG,EAAE,IAAI,CAAC,CAAC;IAC3B,CAAC;IAAC,OAAO,KAAK,EAAE,CAAC;QACf,IAAI,CAAC,KAAK,CAAC,CAAC;IACd,CAAC;AACH,CAAC,CAAC;AAEJ,kBAAe,UAAU,CAAC","sourcesContent":["import { NextFunction, Request, RequestHandler, Response } from 'express';\n\nconst catchAsync =\n  (fn: RequestHandler) =>\n  async (req: Request, res: Response, next: NextFunction): Promise<void> => {\n    try {\n      await fn(req, res, next);\n    } catch (error) {\n      next(error);\n    }\n  };\n\nexport default catchAsync;\n"]}